### ISSUE TITLE
Unable to click hyperlinks within project description

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#765]
I am unable to click hyperlinks within project descriptions.

![image](https://user-images.githubusercontent.com/74267818/114275037-3b343a00-99de-11eb-99b8-f8e439e57c13.png)

**Comment by jamespfarrell** [comment]
@mateodaza Is this now fixed with the rich text editor change?

**Comment by mateodaza** [comment]
It will be!

**Comment by positonic** [comment]
part of rich test editor

**Comment by laurenluz** [comment]
So...

- regular copy/pasted links-as-text do not become hyperlinks automatically... you must add them in using the "link" formatting
- links added in using the "link" formatting don't show up blue/underlined

@mateodaza is already working on the latter as per #391 ... but I'm wondering if it is also possible to create automatic links when a full URL is copy/pasted in as text?

here's an example of how it is now (just shows up as text):
![image](https://user-images.githubusercontent.com/75490971/118310721-39153d80-b4ac-11eb-9429-14a3b92a72df.png)

**Comment by divine-comedian** [comment]
bumping this issue

links still do not auto-resolve in rich text nor do they show up underlined and in blue, nothing identifies them as links actually until you hove over the text and your mouse pointer changes.. 

![image](https://user-images.githubusercontent.com/67759413/119266640-9f3f4600-bbb9-11eb-9316-86946695525f.png)
 
 (the top instance of google.ca I linked using the rich text editor)
